# This is a basic workflow to help you get started with Actions 0389905577

name: vietsub_build

on:
  workflow_dispatch:
  watch:
    types: [started]
    
env:              
  ROM_URL: 'https://bigota.d.miui.com/21.11.24/miui_RAPHAEL_21.11.24_34c2411b8d_11.0.zip'
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@v2
       
       - name: Clean Up
         run: |       
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           df -h
           
       - name: Setting up
         run: |
            sudo apt-get install -y git wget zip unzip img2simg simg2img brotli
           
       - name: Download zip... and run
         run: |
            cd $GITHUB_WORKSPACE/MIUI_VIETSUB
            chmod +x download.sh
            chmod +x bhlnk.sh
            sudo bash download.sh $ROM_URL 
       - name: Upload to transfer
         run: |
            cd $GITHUB_WORKSPACE/MIUI_VIETSUB
            zip_name=$(ls *.zip | grep "vietsub")
            curl --upload-file $zip_name https://transfer.sh/"$zip_name"

