# This is a basic workflow to help you get started with Actions 0389905577

name: vietsub_build

on:
  workflow_dispatch:
  watch:
    types: [started]
    
env:              
  ROM_URL: 'http://172.245.75.15/Mix2_MIUI14.zip'
  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Clean Up
         run: |       
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           df -h
           
       - name: Setting up
         run: |
            sudo apt-get install -y git wget zip unzip img2simg simg2img brotli
           
       - name: Download zip... and run
         run: |
            cd $GITHUB_WORKSPACE
            chmod +x download.sh
            chmod +x bhlnk.sh
            sudo bash download.sh $ROM_URL 
        - name: Upload 
         uses: Difegue/action-megacmd@1.2.0
         with:
          args: put $(ls | grep "Rom") /
         env:
          USERNAME: ${{ github.event.inputs.email }} 
          PASSWORD: ${{ github.event.inputs.pwd }}
